inherit_gem:
  rubocop-rails-omakase: rubocop.yml

# Exclude CSS files from Rubocop - they should be linted by CSS-specific tools
AllCops:
  Exclude:
    - 'app/**/*.css'
    - 'spec/**/*.css'
    - 'vendor/**/*.css'
  
Layout/IndentationWidth:
  Enabled: true

Layout/IndentationStyle:
  EnforcedStyle: spaces
  IndentationWidth: 2

Layout/IndentationConsistency:
  Enabled: true

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: true