# ===========================================================================
# Example Docker Compose file
# ===========================================================================
#
# Purpose:
# --------
#
# This file is an example Docker Compose configuration for self hosting
# Permoney on your local machine or on a cloud VPS.
#
# The configuration below is a "standard" setup that works out of the box,
# but if you're running this outside of a local network, it is recommended
# to set the environment variables for extra security.

version: '3.9'

services:
  web:
# Setup:
# ------
#
# To run this, you should read the setup guide:
#
# https://github.com/hendripermana/permoney/blob/main/docs/hosting/docker.md
#
# Troubleshooting:
# ----------------
#
# If you run into problems, please open an issue on GitHub:
#
# https://github.com/hendripermana/permoney/issues
#

x-db-env: &db_env
  POSTGRES_USER: ${POSTGRES_USER:-permoney_user}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-permoney_password}
  POSTGRES_DB: ${POSTGRES_DB:-permoney_production}

x-rails-env: &rails_env
  <<: *db_env
  # SECURITY: You MUST generate a unique secret key for your deployment.
  # Run `openssl rand -hex 64` to generate one, then set it in your .env file:
  # SECRET_KEY_BASE=your_generated_key_here
  # If SECRET_KEY_BASE is not set, the application will fail to start.
  SECRET_KEY_BASE: ${SECRET_KEY_BASE:?SECRET_KEY_BASE is not set. Please generate one and add it to your .env file.}
  SELF_HOSTED: "true"
  RAILS_FORCE_SSL: "false"
  RAILS_ASSUME_SSL: "false"
  DB_HOST: db
  DB_PORT: 5432
  REDIS_URL: redis://redis:6379/1
# NOTE: enabling OpenAI will incur costs when you use AI-related features in the app (chat, rules).  Make sure you have set appropriate spend limits on your account before adding this.
  OPENAI_ACCESS_TOKEN: ${OPENAI_ACCESS_TOKEN}

web:
    image: ghcr.io/hendripermana/permoney:latest
    volumes:
      - app-storage:/rails/storage
      - ./log:/rails/log
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      <<: *rails_env
      # Performance optimizations
      RUBY_YJIT_ENABLE: "1"
      MALLOC_ARENA_MAX: "2"
      # Optional: Enable StackProf for production profiling
      ENABLE_STACK_PROF: "true"
      # Optional: Skylight monitoring (set your token)
      SKYLIGHT_AUTHENTICATION_TOKEN: "${SKYLIGHT_TOKEN:-}"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - permoney_net
    # Health check for web service
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/up || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  worker:
    image: ghcr.io/hendripermana/permoney:latest
    command: bundle exec sidekiq
    volumes:
      - app-storage:/rails/storage
      - ./log:/rails/log
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      <<: *rails_env
      # Performance optimizations
      RUBY_YJIT_ENABLE: "1"
      MALLOC_ARENA_MAX: "2"
      REDIS_URL: redis://redis:6379/0
      SIDEKIQ_CONCURRENCY: "5"
      # Optional: StackProf for performance monitoring
      ENABLE_STACK_PROF: "true"
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'sidekiq' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - permoney_net

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      <<: *db_env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - permoney_net

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - permoney_net

volumes:
  app-storage:
  postgres-data:
  redis-data:

networks:
  permoney_net:
    driver: bridge
