# ===========================================================================
# Example Docker Compose file
# ===========================================================================
#
# Purpose:
# --------
#
# This file is an example Docker Compose configuration for self hosting
# Permoney on your local machine or on a cloud VPS.
#
# The configuration below is a "standard" setup that works out of the box,
# but if you're running this outside of a local network, it is recommended
# to set the environment variables for extra security.

version: "3.9"

# Setup:
# ------
#
# To run this, read the setup guide:
# https://github.com/hendripermana/permoney/blob/main/docs/hosting/docker.md
#
# Troubleshooting:
# ----------------
#
# If you run into problems, please open an issue on GitHub:
# https://github.com/hendripermana/permoney/issues

x-db-env: &db_env
  POSTGRES_USER: ${POSTGRES_USER:-permoney_user}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-permoney_password}
  POSTGRES_DB: ${POSTGRES_DB:-permoney_production}

x-rails-env: &rails_env
  <<: *db_env
  SECRET_KEY_BASE: ${SECRET_KEY_BASE:?SECRET_KEY_BASE is required (generate via openssl rand -hex 64).}
  RAILS_ENV: production
  RACK_ENV: production
  RAILS_SERVE_STATIC_FILES: "true"
  RAILS_LOG_TO_STDOUT: "true"
  SELF_HOSTED: "true"
  RAILS_FORCE_SSL: "false"
  RAILS_ASSUME_SSL: "false"
  DB_HOST: db
  DB_PORT: 5432
  REDIS_URL: redis://redis:6379/1
  DB_POOL: ${DB_POOL:-52}
  DB_CHECKOUT_TIMEOUT: ${DB_CHECKOUT_TIMEOUT:-5}
  SIDEKIQ_CONCURRENCY: ${SIDEKIQ_CONCURRENCY:-15}
  SIDEKIQ_TIMEOUT: ${SIDEKIQ_TIMEOUT:-90}
  WEB_CONCURRENCY: ${WEB_CONCURRENCY:-4}
  RAILS_MAX_THREADS: ${RAILS_MAX_THREADS:-8}
  OPENAI_ACCESS_TOKEN: ${OPENAI_ACCESS_TOKEN}

x-app-base: &app_base
  image: ${PERMONEY_IMAGE:-ghcr.io/hendripermana/permoney:latest}
  restart: unless-stopped
  volumes:
    - app-storage:/rails/storage
  environment:
    <<: *rails_env
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_healthy
  networks:
    - permoney_net

services:
  web:
    <<: *app_base
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/up || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  worker:
    <<: *app_base
    command: bundle exec sidekiq
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f sidekiq || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:18
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/18/docker
    environment:
      <<: *db_env
      PGDATA: /var/lib/postgresql/18/docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - permoney_net

  redis:
    image: redis:8.2.2
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: >
      redis-server \
      --maxmemory 512mb \
      --maxmemory-policy allkeys-lru \
      --save 60 1000
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - permoney_net

volumes:
  app-storage:
  postgres-data:
  redis-data:

networks:
  permoney_net:
    driver: bridge
