-- PER-16 / M2-2: database-level financial integrity constraints.
--
-- The application validates these invariants before writes, but the database
-- must reject direct SQL, scripts, or future entry points that bypass app code.

-- Supported currency registry. The table name follows PER-16 terminology, but
-- the supported set is intentionally sourced from src/lib/data/currencies.ts,
-- which currently includes ISO-like application-supported codes such as USDC.
CREATE TABLE iso_4217_currency (
  code TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,

  CONSTRAINT iso_4217_currency_pkey PRIMARY KEY (code),
  CONSTRAINT iso_4217_currency_code_shape CHECK (code ~ '^[A-Z]{3,5}$')
);

-- Generated by `vp exec tsx scripts/generate-currency-registry-sql.ts`.
-- Source of truth: src/lib/data/currencies.ts
INSERT INTO iso_4217_currency (code, is_active) VALUES
  ('AED', true),
  ('AFN', true),
  ('ALL', true),
  ('AMD', true),
  ('ANG', true),
  ('AOA', true),
  ('ARS', true),
  ('AUD', true),
  ('AWG', true),
  ('AZN', true),
  ('BAM', true),
  ('BBD', true),
  ('BDT', true),
  ('BGN', true),
  ('BHD', true),
  ('BIF', true),
  ('BMD', true),
  ('BND', true),
  ('BOB', true),
  ('BRL', true),
  ('BSD', true),
  ('BTC', true),
  ('BTN', true),
  ('BWP', true),
  ('BYN', true),
  ('BYR', true),
  ('BZD', true),
  ('CAD', true),
  ('CDF', true),
  ('CHF', true),
  ('CLF', true),
  ('CLP', true),
  ('CNH', true),
  ('CNY', true),
  ('COP', true),
  ('CRC', true),
  ('CUC', true),
  ('CUP', true),
  ('CVE', true),
  ('CZK', true),
  ('DJF', true),
  ('DKK', true),
  ('DOP', true),
  ('DZD', true),
  ('EGP', true),
  ('ERN', true),
  ('ETB', true),
  ('EUR', true),
  ('FJD', true),
  ('FKP', true),
  ('GBP', true),
  ('GBX', true),
  ('GEL', true),
  ('GGP', true),
  ('GHS', true),
  ('GIP', true),
  ('GMD', true),
  ('GNF', true),
  ('GTQ', true),
  ('GYD', true),
  ('HKD', true),
  ('HNL', true),
  ('HTG', true),
  ('HUF', true),
  ('IDR', true),
  ('ILS', true),
  ('IMP', true),
  ('INR', true),
  ('IQD', true),
  ('IRR', true),
  ('ISK', true),
  ('JEP', true),
  ('JMD', true),
  ('JOD', true),
  ('JPY', true),
  ('KES', true),
  ('KGS', true),
  ('KHR', true),
  ('KMF', true),
  ('KPW', true),
  ('KRW', true),
  ('KWD', true),
  ('KYD', true),
  ('KZT', true),
  ('LAK', true),
  ('LBP', true),
  ('LKR', true),
  ('LRD', true),
  ('LSL', true),
  ('LYD', true),
  ('MAD', true),
  ('MDL', true),
  ('MGA', true),
  ('MKD', true),
  ('MMK', true),
  ('MNT', true),
  ('MOP', true),
  ('MRU', true),
  ('MUR', true),
  ('MVR', true),
  ('MWK', true),
  ('MXN', true),
  ('MYR', true),
  ('MZN', true),
  ('NAD', true),
  ('NGN', true),
  ('NIO', true),
  ('NOK', true),
  ('NPR', true),
  ('NZD', true),
  ('OMR', true),
  ('PAB', true),
  ('PEN', true),
  ('PGK', true),
  ('PHP', true),
  ('PKR', true),
  ('PLN', true),
  ('PYG', true),
  ('QAR', true),
  ('RON', true),
  ('RSD', true),
  ('RUB', true),
  ('RWF', true),
  ('SAR', true),
  ('SBD', true),
  ('SCR', true),
  ('SDG', true),
  ('SEK', true),
  ('SGD', true),
  ('SHP', true),
  ('SKK', true),
  ('SLE', true),
  ('SLL', true),
  ('SOS', true),
  ('SRD', true),
  ('SSP', true),
  ('STD', true),
  ('STN', true),
  ('SVC', true),
  ('SYP', true),
  ('SZL', true),
  ('THB', true),
  ('TJS', true),
  ('TMT', true),
  ('TND', true),
  ('TOP', true),
  ('TRY', true),
  ('TTD', true),
  ('TWD', true),
  ('TZS', true),
  ('UAH', true),
  ('UGX', true),
  ('USD', true),
  ('USDC', true),
  ('UYU', true),
  ('UZS', true),
  ('VES', true),
  ('VND', true),
  ('VUV', true),
  ('WST', true),
  ('XAF', true),
  ('XAG', true),
  ('XAU', true),
  ('XBA', true),
  ('XBB', true),
  ('XBC', true),
  ('XBD', true),
  ('XCD', true),
  ('XDR', true),
  ('XFU', true),
  ('XOF', true),
  ('XPD', true),
  ('XPF', true),
  ('XPT', true),
  ('XTS', true),
  ('YER', true),
  ('ZAR', true),
  ('ZMK', true),
  ('ZMW', true);

-- Signed amount must match the transaction direction. Transfers remain signed
-- by their individual ledger leg and are paired by later double-entry work.
ALTER TABLE "Transaction"
  ADD CONSTRAINT transaction_type_domain CHECK (
    "type" IN ('expense', 'income', 'transfer')
  );

ALTER TABLE "Transaction"
  ADD CONSTRAINT transaction_status_domain CHECK (
    "status" IN ('PENDING', 'CLEARED', 'RECONCILED')
  );

ALTER TABLE "Transaction"
  ADD CONSTRAINT transaction_kind_domain CHECK (
    "kind" IN ('standard', 'funds_movement', 'cc_payment', 'loan_payment')
  );

ALTER TABLE "Transaction"
  ADD CONSTRAINT amount_sign_matches_type CHECK (
    ("type" = 'expense' AND "amount" <= 0) OR
    ("type" = 'income' AND "amount" >= 0) OR
    ("type" = 'transfer')
  );

ALTER TABLE "Transaction"
  ADD CONSTRAINT currency_is_iso_4217
  FOREIGN KEY ("currency") REFERENCES iso_4217_currency(code)
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "Transaction"
  ADD CONSTRAINT destination_currency_is_iso_4217
  FOREIGN KEY ("destinationCurrency") REFERENCES iso_4217_currency(code)
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "Family"
  ADD CONSTRAINT family_currency_is_iso_4217
  FOREIGN KEY ("currency") REFERENCES iso_4217_currency(code)
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "Account"
  ADD CONSTRAINT account_currency_is_iso_4217
  FOREIGN KEY ("currency") REFERENCES iso_4217_currency(code)
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "Transaction"
  ADD CONSTRAINT destination_pair_consistency CHECK (
    ("destinationAmount" IS NULL AND "destinationCurrency" IS NULL) OR
    ("destinationAmount" IS NOT NULL AND "destinationCurrency" IS NOT NULL)
  );

ALTER TABLE "Account"
  ADD CONSTRAINT account_type_domain CHECK (
    "type" IN ('DEPOSITORY', 'CREDIT', 'LOAN', 'RECEIVABLE', 'INVESTMENT')
  );

ALTER TABLE "Account"
  ADD CONSTRAINT account_status_domain CHECK (
    "status" IN ('active', 'closed')
  );

ALTER TABLE "Account"
  ADD CONSTRAINT balance_nonneg_for_asset_accounts CHECK (
    "type" IN ('CREDIT', 'LOAN', 'RECEIVABLE') OR "balance" >= 0
  );

ALTER TABLE "Transaction"
  ADD CONSTRAINT split_parent_details_live_on_children CHECK (
    "isSplit" = false OR ("categoryId" IS NULL AND "merchantId" IS NULL)
  );

ALTER TABLE "SplitEntry"
  ADD CONSTRAINT amount_positive CHECK ("amount" > 0);

-- PostgreSQL CHECK constraints cannot look across rows, so split parity is
-- enforced with a deferred constraint trigger. This lets the app insert the
-- parent transaction first and its split entries afterward inside one
-- transaction, while still rejecting an invalid final ledger graph at COMMIT.
CREATE FUNCTION validate_split_entries_match_parent(transaction_id TEXT)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  parent_amount BIGINT;
  parent_is_split BOOLEAN;
  split_total BIGINT;
BEGIN
  IF transaction_id IS NULL THEN
    RETURN;
  END IF;

  SELECT "amount", "isSplit"
  INTO parent_amount, parent_is_split
  FROM "Transaction"
  WHERE id = transaction_id;

  IF NOT FOUND OR parent_is_split = false THEN
    RETURN;
  END IF;

  SELECT COALESCE(SUM("amount"), 0)::BIGINT
  INTO split_total
  FROM "SplitEntry"
  WHERE "transactionId" = transaction_id;

  IF split_total <> ABS(parent_amount) THEN
    RAISE EXCEPTION
      'SplitEntries sum (%) must equal absolute parent amount (%) for transaction %',
      split_total,
      ABS(parent_amount),
      transaction_id
      USING
        ERRCODE = '23514',
        CONSTRAINT = 'split_entries_match_parent_amount';
  END IF;
END;
$$;

CREATE FUNCTION enforce_split_entries_match_parent()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_TABLE_NAME = 'SplitEntry' THEN
    IF TG_OP IN ('UPDATE', 'DELETE') THEN
      PERFORM validate_split_entries_match_parent(OLD."transactionId");
    END IF;

    IF TG_OP IN ('INSERT', 'UPDATE') THEN
      PERFORM validate_split_entries_match_parent(NEW."transactionId");
    END IF;
  ELSE
    IF TG_OP IN ('INSERT', 'UPDATE') THEN
      PERFORM validate_split_entries_match_parent(NEW.id);
    END IF;
  END IF;

  RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER transaction_split_entries_match_parent_amount
AFTER INSERT OR UPDATE OF "amount", "isSplit" ON "Transaction"
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION enforce_split_entries_match_parent();

CREATE CONSTRAINT TRIGGER split_entry_entries_match_parent_amount
AFTER INSERT OR UPDATE OF "amount", "transactionId" OR DELETE ON "SplitEntry"
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION enforce_split_entries_match_parent();
