# frozen_string_literal: true

# This migration cleans up orphaned balance records that have a currency different
# from their account's current currency. This can happen when linked accounts
# (SimpleFIN, Lunchflow, Enable Banking, Plaid) were created with an initial sync
# before the correct currency was known from the provider.
#
# The fix in Account.create_and_sync with skip_initial_sync: true prevents this
# going forward, but existing data needs to be cleaned up.
class CleanupOrphanedCurrencyBalances < ActiveRecord::Migration[7.2]
  def up
    # First, identify affected accounts for logging
    affected_accounts = execute(<<~SQL).to_a
      SELECT DISTINCT
        a.id,
        a.name,
        a.currency as account_currency,
        b.currency as orphaned_currency,
        COUNT(b.id) as orphaned_balance_count
      FROM accounts a
      JOIN balances b ON a.id = b.account_id
      WHERE a.currency != b.currency
      GROUP BY a.id, a.name, a.currency, b.currency
    SQL

    if affected_accounts.any?
      say "Found #{affected_accounts.size} accounts with orphaned currency balances:"

      affected_accounts.each do |row|
        say "  - #{row['name']} (ID: #{row['id']}): " \
            "#{row['orphaned_balance_count']} balances in #{row['orphaned_currency']} " \
            "(account currency is #{row['account_currency']})"
      end

      # Delete orphaned balances
      account_ids = affected_accounts.map { |row| row["id"] }

      deleted_count = execute(
        "DELETE FROM balances WHERE account_id = ANY($1::uuid[]) AND currency != (SELECT currency FROM accounts WHERE id = account_id)",
        [ account_ids ]
      )

      say "Deleted #{deleted_count} orphaned balance records"

      # Re-sync affected accounts to regenerate balances with correct currency
      Account.where(id: account_ids).find_each do |account|
        account.sync_later
      end

      say "Scheduled re-sync for #{account_ids.size} affected accounts"
    else
      say "No orphaned currency balances found - database is clean"
    end
  end

  def down
    say "This migration cannot be fully reversed."
    say "The deleted balances will be regenerated by the scheduled syncs."
    say "If syncs haven't run yet, you may need to manually trigger them."
  end
end
