import { CURRENCIES } from "../src/lib/data/currencies"

const CURRENCY_CODE_PATTERN = /^[A-Z]{3,5}$/

const currencyCodes = Object.keys(CURRENCIES).sort((left, right) =>
  left.localeCompare(right)
)

for (const code of currencyCodes) {
  if (!CURRENCY_CODE_PATTERN.test(code)) {
    throw new Error(`Unsupported database currency code shape: ${code}`)
  }
}

const values = currencyCodes.map((code, index) => {
  const suffix = index === currencyCodes.length - 1 ? ";" : ","
  return `  ('${code}', true)${suffix}`
})

console.log(
  [
    "-- Generated by `vp exec tsx scripts/generate-currency-registry-sql.ts`.",
    "-- Source of truth: src/lib/data/currencies.ts",
    "INSERT INTO iso_4217_currency (code, is_active) VALUES",
    ...values,
  ].join("\n")
)
