name: React Doctor

on:
  pull_request:

permissions:
  checks: write # required to create/update the React Doctor check run
  contents: read
  pull-requests: write # required to post PR comments

jobs:
  react-doctor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: millionco/react-doctor@6d53182f7333b29d5168dcd311c1d5f18e95e072
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
