name: React Doctor

on:
  pull_request:

permissions:
  checks: write # required to create/update the React Doctor check run
  contents: read
  pull-requests: write # required to post PR comments

jobs:
  react-doctor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: millionco/react-doctor@6216430f93404489f6a56b4d0a7c196beb86623a
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
